### ISSUE TITLE
Errors not handled properly

### ISSUE THREAD

**Issue by ashleshashinde** [airavata-courses/CAPtivate#57]
Error codes are displayed directly on the frontend

**Comment by adithyaselv** [comment]
Thanks for reporting! Can you please describe a bit in detail on how to reproduce the issue ?

**Comment by ashleshashinde** [comment]
When i clicked on fetch jobs, an error code was displayed on the screen

**Comment by adithyaselv** [comment]
Cool ! Thanks we will look into it .

**Comment by adithyaselv** [comment]
fixed in #64 can you please check ?
