### ISSUE TITLE
User Login, if the jobs feature is accessed it logs out the User

### ISSUE THREAD

**Issue by CleverParty** [airavata-courses/CAPtivate#60]
After the user is logged in,if the user tries to access jobs,  i am logged out.\
the flow goes like -- > http://localhost:3000/login to http://localhost:3000/dashboard and then to -->http://localhost:3000/login after the user has been registered
is something I'm doing wrong in the login flow ? or do you think I am missing any dependency?

**Comment by CleverParty** [comment]
{'user_id': 'tester@gmail.com', 'job_id': 'c7068368-de7a-4e48-9805-eddb7a2d2419', 'location_id': 'ZIP:47408', 'date': '2019-02-10', 'tmax': -1.7}
 that is the data-retrieval.py server log after job has been submitted on /dashboard

{'user_id': 'tester@gmail.com', 'job_id': 'c7068368-de7a-4e48-9805-eddb7a2d2419', 'location_id': 'ZIP:47408', 'date': '2019-02-10', 'tmax': -1.7}
this is the  postprocessing-analysis.py server log

**Comment by rasmitha-koduru** [comment]
> After the user is logged in,if the user tries to access jobs, i am logged out.
> the flow goes like -- > http://localhost:3000/login to http://localhost:3000/dashboard and then to -->http://localhost:3000/login after the user has been registered
> is something I'm doing wrong in the login flow ? or do you think I am missing any dependency?

No, you are doing it correct. Right now jobs on the side bar is logging you out. There is an other jobs page on the nav bar which will take you to fetch jobs.
Will be fixing the sidebar routing.
Thanks a lot for reporting!

**Comment by adithyaselv** [comment]
@rasmitha-koduru should we remove the sidebar all together for now ? lets not have buggy one in the UI for now . Lets make it work and add it . You could create a PR removing the sidebar. and then we can add a working one ... What do you think ?

**Comment by rasmitha-koduru** [comment]
yeah i was thinking of disabling it for now, sure ill create a PR @adithyaselv

**Comment by CleverParty** [comment]
Verified , the linking now works.
