### ISSUE TITLE
Status field showing In-Progress even after fetching the jobs 

### ISSUE THREAD

**Issue by adithyaselv** [airavata-courses/CAPtivate#73]
Jobs page in UI shows status as fetching even after the job is already fetched. 

![cap-bug](https://user-images.githubusercontent.com/1871941/74608315-fa78b380-50ad-11ea-8b8a-c76fe691d466.png)

**Comment by rasmitha-koduru** [comment]
Let me reproduce and check. Thanks for reporting!

**Comment by adithyaselv** [comment]
@rasmitha-koduru I found the root cause of the issue to be in data-retrieval service and I am working on a proper fix here #74 . it is not related to UI
